version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:6.4
    container_name: elasticsearch
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - plantsnet

volumes:
  esdata1:

networks:
  plantsnet:
